# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4b6748d7cb4234f8a74f68356b7378b2817a499e1bd2b4d6427e2effa297f9e3d77dba18fd78d7d297730c748d1a69796757c21ffe7177339761aca7097c7e1

test:
  secret_key_base: 52f2f9d7f63b4141501f8547d097f011fd297ea1f2a81eedee66a482a666ed4d3f9b21162775c32599a6087c5073a9829492f557c183a8a425bd62739175542f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
